### ISSUE TITLE
Incompatibility with phoenix_live_view 0.18.18

### ISSUE THREAD

**Issue by haslinger** [surface-ui/surface#686]
I see a compilation error for Surface 0.9.4, when I'm trying to upgrade from phoenix_live_view 0.18.14 to 0.18.18

```bash
==> surface
Compiling 145 files (.ex)

== Compilation error in file lib/surface/components/form.ex ==
** (CompileError) lib/surface/components/form.ex:101: the function "inner_block" cannot handle clauses with the -> operator because it is not a macro. Please make sure you are invoking the proper name and that it is a macro
    expanding macro: Surface.sigil_F/2
could not compile dependency :surface, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile surface", update it with "mix deps.update surface" or clean it with "mix deps.clean surface"
```

my environment is
```bash
$ cat /etc/issue
Ubuntu 22.04.2 LTS
$ uname -a
Linux indigo 5.15.0-67-generic #74-Ubuntu SMP Wed Feb 22 14:14:39 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
$ elixir --version
Erlang/OTP 25 [erts-13.1.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [jit:ns]
Elixir 1.14.1 (compiled with Erlang/OTP 25)
```

Happy to provide any more information.

Update: it still compiles fine with phoenix_live_view 0.18.16, it fails first for 0.18.17

**Comment by travelmassive** [comment]
This is the same as #683 and is fixed in PR #684 

Just waiting on a new release from the authors :)

~ Ian

**Comment by msaraiva** [comment]
Closed in #687.
