### ISSUE TITLE
Compile error on form.ex

### ISSUE THREAD

**Issue by travelmassive** [surface-ui/surface#683]
I get a compiler error on form.ex

```== Compilation error in file lib/surface/components/form.ex ==
** (CompileError) lib/surface/components/form.ex:101: the function "inner_block" cannot handle clauses with the -> operator because it is not a macro. Please make sure you are invoking the proper name and that it is a macro
    expanding macro: Surface.sigil_F/2
```

Have tried clean build, etc. 

## Your Environment
Surface: v0.9.4
LiveView: v0.18.17
Elixir: v1.14.3

**Comment by hrvelic** [comment]
I can confirm that this error appears only with LiveView 0.18.17. Compiles fine with 0.18.16.

**Comment by travelmassive** [comment]
Can confirm that PR #684 allows to compile with LiveView 0.18.18, thanks @frankdugan3! ~ Ian

**Comment by CAJazzer** [comment]
Fails for me with

Surface: v0.9.4
LiveView: v0.18.16
Elixir: v1.14.3

**Comment by msaraiva** [comment]
Closed in #687.

**Comment by goto-engineering** [comment]
Still getting this error with LV at `0.18.18` and Surface at `0.9.4`.
Do I need to upgrade Phoenix to 1.7 for this to work again?

**Comment by skanderm** [comment]
> Still getting this error with LV at `0.18.18` and Surface at `0.9.4`. Do I need to upgrade Phoenix to 1.7 for this to work again?

Seems the fix needs to go out on the next release, or if you'd like:

` {:surface, git: "git@github.com:surface-ui/surface.git", ref: "c818bbd", override: true}`

**Comment by CAJazzer** [comment]
@goto-engineering You can get your code to compile if you add the fixed code files from @frankdugan3.  Download these files [here](https://github.com/surface-ui/surface/pull/684/files) and re-compile.  Should work.

**Comment by goto-engineering** [comment]
@CAJazzer Thanks, it seems that adding a dep of `{:phoenix_view, "~> 2.0"}` also fixed it :shrug: Found that on the Elixir forum.
