### ISSUE TITLE
Unicode conversion error in attribute value

### ISSUE THREAD

**Issue by fdeage** [surface-ui/surface#497]
## Describe the bug

Using unicode text in an expression used as attribute value raises a `UnicodeConversionError` error.

## How to reproduce it

`elixir
defmodule MyAppWeb.Components.Hello do
  use Surface.Component

  property(test, :string)

  def render(assigns) do
    ~H"""
    <div :if={{ @test == "é" }}>
      Hello
    </div>
    """
  end
end
`

## The behavior you expected

No error raised, the expression evaluates to a boolean.

## Your Environment

Surface: msaraiva/surface@master
LiveView: v0.13.3
Elixir: v1.12.2

## Stacktrace

`
== Compilation error in file lib/my_app_web/live/hello_live/hello_test.ex ==
** (UnicodeConversionError) invalid encoding starting at <<233, 34>>
    (elixir 1.12.2) lib/list.ex:961: List.to_string/1
    (surface 0.1.0-alpha.2) expanding macro: Surface.sigil_H/2
    lib/my_app_web/live/hello_live/hello_test.ex:7: MyAppWeb.HelloLive.HelloTest.render/1
    (elixir 1.12.2) lib/kernel/parallel_compiler.ex:319: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7
`

**Comment by davydog187** [comment]
@fdeage can test against the `master` branch to confirm this has fixed your issue?

**Comment by fdeage** [comment]
Thanks @msaraiva for the answer.

Actually I am tracking the master branch (`{:surface, github: "msaraiva/surface", branch: "master"},`), but my `mix.lock` locks Surface on commit `28a53e74cd7923cd` (`0.1.0-alpha.2`) for some reason.

Forcing `"~> 0.5"` gives me a compilation error:
`== Compilation error in file lib/surface/components/live_file_input.ex ==
** (CompileError) lib/surface/components/live_file_input.ex:37: undefined function live_file_input/2
    (elixir 1.12.2) src/elixir_locals.erl:114: anonymous fn/3 in :elixir_locals.ensure_no_undefined_local/3
    (stdlib 3.15.2) erl_eval.erl:685: :erl_eval.do_apply/6
    (elixir 1.12.2) lib/kernel/parallel_compiler.ex:319: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7`

Btw, `0.1.0-alpha.2` is still after the merge of the PR I mentionned, so I really have no clue of why the same error keeps coming...
